Fix AttributeError for ImageAssembler in PretrainedPipeline (#12813)
- When PretrainedPipeline is used in Python with ImageAssembler it will fail with `AttributeError: module 'sparknlp' has no attribute 'ImageAssembler'`